blank_issues_enabled: false

labels:
  - bug
  - enhancement
  - documentation

body:
  - type: markdown
    attributes:
      value: "## Select issue type:"
  - type: dropdown
    id: type
    attributes:
      label: "Type"
      description: "Choose the type of issue"
      options:
        - "[Bug] Report"
        - "[Enhancement] Feature request"
        - "[Docs] Documentation"
      default: 0
      required: true
